/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as Showroom3dRouteImport } from './routes/showroom-3d'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const Showroom3dRoute = Showroom3dRouteImport.update({
  id: '/showroom-3d',
  path: '/showroom-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/projetos/$projectId',
  path: '/projetos/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/showroom-3d': typeof Showroom3dRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/showroom-3d': typeof Showroom3dRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/showroom-3d': typeof Showroom3dRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/showroom-3d'
    | '/sitemap.xml'
    | '/projetos/$projectId'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/showroom-3d'
    | '/sitemap.xml'
    | '/projetos/$projectId'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/showroom-3d'
    | '/sitemap.xml'
    | '/projetos/$projectId'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  Showroom3dRoute: typeof Showroom3dRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom-3d': {
      id: '/showroom-3d'
      path: '/showroom-3d'
      fullPath: '/showroom-3d'
      preLoaderRoute: typeof Showroom3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$projectId': {
      id: '/projetos/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  Showroom3dRoute: Showroom3dRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
