/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LinksRouteImport } from './routes/links'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Showroom3dRouteImport } from './routes/showroom-3d'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ApiLeadsRouteImport } from './routes/api.leads'
import { Route as MoveisPlanejadosEmCidadeRouteImport } from './routes/moveis-planejados-em.$cidade'
import { Route as MoveisPlanejadosIndexRouteImport } from './routes/moveis-planejados.index'
import { Route as MoveisPlanejadosServicoRouteImport } from './routes/moveis-planejados.$servico'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Showroom3dRoute = Showroom3dRouteImport.update({
  id: '/showroom-3d',
  path: '/showroom-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveisPlanejadosEmCidadeRoute =
  MoveisPlanejadosEmCidadeRouteImport.update({
    id: '/moveis-planejados-em/$cidade',
    path: '/moveis-planejados-em/$cidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const MoveisPlanejadosIndexRoute = MoveisPlanejadosIndexRouteImport.update({
  id: '/moveis-planejados/',
  path: '/moveis-planejados/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveisPlanejadosServicoRoute = MoveisPlanejadosServicoRouteImport.update({
  id: '/moveis-planejados/$servico',
  path: '/moveis-planejados/$servico',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/projetos/$projectId',
  path: '/projetos/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/links': typeof LinksRoute
  '/orcamento': typeof OrcamentoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/showroom-3d': typeof Showroom3dRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/leads': typeof ApiLeadsRoute
  '/moveis-planejados-em/$cidade': typeof MoveisPlanejadosEmCidadeRoute
  '/moveis-planejados/$servico': typeof MoveisPlanejadosServicoRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/moveis-planejados/': typeof MoveisPlanejadosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/links': typeof LinksRoute
  '/orcamento': typeof OrcamentoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/showroom-3d': typeof Showroom3dRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/leads': typeof ApiLeadsRoute
  '/moveis-planejados-em/$cidade': typeof MoveisPlanejadosEmCidadeRoute
  '/moveis-planejados/$servico': typeof MoveisPlanejadosServicoRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/moveis-planejados': typeof MoveisPlanejadosIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/links': typeof LinksRoute
  '/orcamento': typeof OrcamentoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/showroom-3d': typeof Showroom3dRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/leads': typeof ApiLeadsRoute
  '/moveis-planejados-em/$cidade': typeof MoveisPlanejadosEmCidadeRoute
  '/moveis-planejados/$servico': typeof MoveisPlanejadosServicoRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/moveis-planejados/': typeof MoveisPlanejadosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/links'
    | '/orcamento'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/showroom-3d'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/leads'
    | '/moveis-planejados-em/$cidade'
    | '/moveis-planejados/$servico'
    | '/projetos/$projectId'
    | '/moveis-planejados/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/links'
    | '/orcamento'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/showroom-3d'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/leads'
    | '/moveis-planejados-em/$cidade'
    | '/moveis-planejados/$servico'
    | '/projetos/$projectId'
    | '/moveis-planejados'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/links'
    | '/orcamento'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/showroom-3d'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/leads'
    | '/moveis-planejados-em/$cidade'
    | '/moveis-planejados/$servico'
    | '/projetos/$projectId'
    | '/moveis-planejados/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  LinksRoute: typeof LinksRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  Showroom3dRoute: typeof Showroom3dRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  MoveisPlanejadosEmCidadeRoute: typeof MoveisPlanejadosEmCidadeRoute
  MoveisPlanejadosServicoRoute: typeof MoveisPlanejadosServicoRoute
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
  MoveisPlanejadosIndexRoute: typeof MoveisPlanejadosIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom-3d': {
      id: '/showroom-3d'
      path: '/showroom-3d'
      fullPath: '/showroom-3d'
      preLoaderRoute: typeof Showroom3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moveis-planejados-em/$cidade': {
      id: '/moveis-planejados-em/$cidade'
      path: '/moveis-planejados-em/$cidade'
      fullPath: '/moveis-planejados-em/$cidade'
      preLoaderRoute: typeof MoveisPlanejadosEmCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moveis-planejados/': {
      id: '/moveis-planejados/'
      path: '/moveis-planejados'
      fullPath: '/moveis-planejados/'
      preLoaderRoute: typeof MoveisPlanejadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moveis-planejados/$servico': {
      id: '/moveis-planejados/$servico'
      path: '/moveis-planejados/$servico'
      fullPath: '/moveis-planejados/$servico'
      preLoaderRoute: typeof MoveisPlanejadosServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$projectId': {
      id: '/projetos/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  LinksRoute: LinksRoute,
  OrcamentoRoute: OrcamentoRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  Showroom3dRoute: Showroom3dRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  MoveisPlanejadosEmCidadeRoute: MoveisPlanejadosEmCidadeRoute,
  MoveisPlanejadosServicoRoute: MoveisPlanejadosServicoRoute,
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
  MoveisPlanejadosIndexRoute: MoveisPlanejadosIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
